inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - db/migrate/*
    - db/schema.rb
    - bin/bundle

Layout/LineLength:
  Max: 150
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake
    - app/admin/**/*

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ModuleLength:
  Max: 200
